### ISSUE TITLE
Avoid paranthesis in single parameter arrow function

### ISSUE THREAD

**Issue by itaditya** [pazams/go-for-javascript-developers#17]
In the code snippet

```js
function fetchSequential() {
    fetchA().then( (a) => {
        console.log(a);
        return fetchB();
    }.then( (b) => {
        console.log(b);
        return fetchC();
    }.then( (c) => {
        console.log(c);
    }
}
```

we should do this 

```js
function fetchSequential() {
    fetchA().then(a => {
        console.log(a);
        return fetchB();
    }).then(b => {
        console.log(b);
        return fetchC();
    }).then(c => {
        console.log(c);
    })
}
```

**Comment by itaditya** [comment]
Also we can do even smaller like this

```js
function fetchSequential() {
  fetchA()
    .then(a => console.log(a), fetchB())
    .then(b => console.log(b), fetchC())
    .then(c => console.log(c))
}
```

**Comment by pazams** [comment]
> we should do this
> 
> function fetchSequential() {
>     fetchA().then(a => {
>         console.log(a);
>         return fetchB();
>     }).then(b => {
>         console.log(b);
>         return fetchC();
>     }).then(c => {
>         console.log(c);
>     })
> }

Please PR this, thanks 👍 
As for the short form, I would prefer to avoid it and keep things more explicit event at the cost of extra lines.

**Comment by itaditya** [comment]
It would be better if you first merge my existing PR so that we don't get merge errors

**Comment by itaditya** [comment]
is this PR  fine or does it need changes ?

**Comment by pazams** [comment]
This is just an issue still :)
Please PR it, thanks 🙏

**Comment by itaditya** [comment]
Oh sorry I forgot ..

**Comment by itaditya** [comment]
hehe just made a PR #22
