### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by chenjinya** [pazams/go-for-javascript-developers#31]
This's an awesome book !!

I have translated it into Chinese

https://github.com/chenjinya/go-for-javascript-developers

**Comment by pazams** [comment]
Thanks @chenjinya for making a translation!

**Comment by pazams** [comment]
@chenjinya I added a link to your translation on the page readme page.
I see you have translator notes that are unresolved - I think I can provide further feedback on them.  Feel free to open issues on this repo to discuss them.

**Comment by pazams** [comment]
Closing as the link was added to main page

**Comment by chenjinya** [comment]
Thanks ~
